name: svce_student_management
description: "A new Flutter project."

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  carousel_slider: ^5.0.0
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_animate: ^4.0.0
  hive_flutter: ^1.1.0
  shared_preferences: ^2.3.3  
  smooth_page_indicator: ^1.0.0+2
  vertical_card_pager: ^1.6.2
  get: ^4.6.6
  video_player: ^2.9.2
  percent_indicator: ^4.2.2
  firebase_core: ^3.8.0
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.5.0
  firebase_storage: ^12.3.6
  firebase_analytics: ^11.3.5
  firebase_crashlytics: ^4.1.5
  firebase_messaging: ^15.1.5
  rive: ^0.13.17
  permission_handler: ^11.0.0
  image_picker: ^1.1.2
  flutter_svg: ^2.0.15

dev_dependencies:
  flutter_lints: ^5.0.0 
  flutter_test:
    sdk: flutter
  flutter_native_splash: ^2.4.3
  hive_generator: ^2.0.1 
  build_runner: ^2.4.2  
  flutter_launcher_icons: ^0.14.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/images/images.png"
  min_sdk_android: 24
  adaptive_icon_background: "#ffffff"
  adaptive_icon_foreground: "assets/images/images.png"

flutter_native_splash:
  image: assets/images/splash_screen.png

flutter:
  uses-material-design: true

  assets:
    - assets/avaters/
    - assets/Backgrounds/
    - assets/icons/
    - assets/RiveAssets/
    - assets/images/

  fonts:
    - family: Acme
      fonts:
        - asset: fonts/asset/Acme-Regular.ttf
    - family: Alatsi
      fonts:
        - asset: fonts/asset/Alatsi-Regular.ttf
          weight: 700
    - family: Arvo
      fonts:
        - asset: fonts/Arvo-Italic.ttf
          weight: 400
          style: italic
        - asset: fonts/Arvo-Bold.ttf
          weight: 600
          style: normal
        - asset: fonts/Arvo-BoldItalic.ttf
          weight: 600
          style: italic
    - family: Intel
      fonts:
        - asset: assets/Fonts/Inter-Regular.ttf
        - asset: assets/Fonts/Inter-SemiBold.ttf
          weight: 600
    - family: Poppins
      fonts:
        - asset: assets/Fonts/Poppins-Bold.ttf
          weight: 700
