// final Map<String, List<ScheduleCard>> schedules = {
//     'Monday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Discrete Mathematics',
//         courseCode: 'MA22353',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Data Structures and Algorithms',
//         courseCode: 'IT22301',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'Database Concepts',
//         courseCode: 'IT22302',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Digital Communication',
//         courseCode: 'IT22303',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'IT Essentials: Theory and Practices',
//         courseCode: 'IT22309',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Data Structures and Algorithms Laboratory',
//         courseCode: 'IT22311',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'Database Concepts Laboratory',
//         courseCode: 'IT22312',
//         section: 'A',
//       ),
//     ],
//     'Tuesday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Digital Communication Laboratory',
//         courseCode: 'IT22313',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Discrete Mathematics',
//         courseCode: 'MA22353',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'Seminar',
//         courseCode: 'SEM',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Placement and Training',
//         courseCode: 'PT',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'Library',
//         courseCode: 'LIB',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Data Structures and Algorithms',
//         courseCode: 'IT22301',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'Database Concepts',
//         courseCode: 'IT22302',
//         section: 'A',
//       ),
//     ],
//     // Additional days can be filled similarly
//     'Wednesday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Database Concepts',
//         courseCode: 'IT22302',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Digital Communication',
//         courseCode: 'IT22303',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'IT Essentials: Theory and Practices',
//         courseCode: 'IT22309',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Database Concepts Laboratory',
//         courseCode: 'IT22312',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'Digital Communication Laboratory',
//         courseCode: 'IT22313',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Discrete Mathematics',
//         courseCode: 'MA22353',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'Placement and Training',
//         courseCode: 'PT',
//         section: 'A',
//       ),
//     ],
//     'Thursday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Data Structures and Algorithms',
//         courseCode: 'IT22301',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Library',
//         courseCode: 'LIB',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'Seminar',
//         courseCode: 'SEM',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Data Structures and Algorithms Laboratory',
//         courseCode: 'IT22311',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'Database Concepts',
//         courseCode: 'IT22302',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Digital Communication',
//         courseCode: 'IT22303',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'IT Essentials: Theory and Practices',
//         courseCode: 'IT22309',
//         section: 'A',
//       ),
//     ],
//     'Friday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Digital Communication Laboratory',
//         courseCode: 'IT22313',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Data Structures and Algorithms',
//         courseCode: 'IT22301',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'Discrete Mathematics',
//         courseCode: 'MA22353',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Placement and Training',
//         courseCode: 'PT',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'Database Concepts Laboratory',
//         courseCode: 'IT22312',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Digital Communication',
//         courseCode: 'IT22303',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'IT Essentials: Theory and Practices',
//         courseCode: 'IT22309',
//         section: 'A',
//       ),
//     ],
//     'Saturday': [
//       ScheduleCard(
//         time: '08:30 AM-09:20 AM',
//         courseName: 'Library',
//         courseCode: 'LIB',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '09:20 AM-10:10 AM',
//         courseName: 'Seminar',
//         courseCode: 'SEM',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '10:25 AM-11:15 AM',
//         courseName: 'Data Structures and Algorithms Laboratory',
//         courseCode: 'IT22311',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '11:15 AM-12:05 PM',
//         courseName: 'Database Concepts',
//         courseCode: 'IT22302',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '12:45 PM-01:35 PM',
//         courseName: 'Digital Communication',
//         courseCode: 'IT22303',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '01:35 PM-02:25 PM',
//         courseName: 'Discrete Mathematics',
//         courseCode: 'MA22353',
//         section: 'A',
//       ),
//       ScheduleCard(
//         time: '02:25 PM-03:15 PM',
//         courseName: 'Data Structures and Algorithms',
//         courseCode: 'IT22301',
//         section: 'A',
//       ),
//     ],
//   };
