// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3XGVAv739EWvb6cb9p23FYFCcOM5uSvY',
    appId: '1:271186284163:web:4447cb23631fc34d6915b6',
    messagingSenderId: '271186284163',
    projectId: 'svce-student-management',
    authDomain: 'svce-student-management.firebaseapp.com',
    storageBucket: 'svce-student-management.firebasestorage.app',
    measurementId: 'G-QKRM8DKK8Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDOTJwUOv8D4_slhioZm_gT2F4XO0BFyyk',
    appId: '1:271186284163:android:2bb7c743158966286915b6',
    messagingSenderId: '271186284163',
    projectId: 'svce-student-management',
    storageBucket: 'svce-student-management.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA3BYORU-_4bI2Cl_7P0Vjjohyaaka3aPc',
    appId: '1:271186284163:ios:9ae48da2508bb9e96915b6',
    messagingSenderId: '271186284163',
    projectId: 'svce-student-management',
    storageBucket: 'svce-student-management.firebasestorage.app',
    iosBundleId: 'com.example.svceStudentManagement',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA3BYORU-_4bI2Cl_7P0Vjjohyaaka3aPc',
    appId: '1:271186284163:ios:9ae48da2508bb9e96915b6',
    messagingSenderId: '271186284163',
    projectId: 'svce-student-management',
    storageBucket: 'svce-student-management.firebasestorage.app',
    iosBundleId: 'com.example.svceStudentManagement',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA3XGVAv739EWvb6cb9p23FYFCcOM5uSvY',
    appId: '1:271186284163:web:e1e88e8955eeba3e6915b6',
    messagingSenderId: '271186284163',
    projectId: 'svce-student-management',
    authDomain: 'svce-student-management.firebaseapp.com',
    storageBucket: 'svce-student-management.firebasestorage.app',
    measurementId: 'G-0YQ58R8ZFK',
  );
}
